version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    open-pull-requests-limit: 10
    labels: ["type: dependency-upgrade"]
    groups:
       development-dependencies:
         update-types: ["patch"]
         patterns: 
         - "com.gradle.enterprise"
         - "io.spring.*"
         - "org.ajoberstar.grgit"
         - "org.antora"
         - "io.micrometer:micrometer-docs-generator"
         - "org.hibernate.validator:hibernate-validator"
         - "org.awaitility:awaitility"
         - "com.google.code.findbugs:jsr305"
         - "org.springframework.boot*"

  - package-ecosystem: "maven"
    directory: "/samples"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels: ["type: task"]
    groups:
      development-dependencies:
        patterns:
          - "*"
